name: MPET Bot Scraper

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code ophalen
        uses: actions/checkout@v4
        with:
          # Dit zorgt ervoor dat de bot de volledige geschiedenis heeft om fouten te voorkomen
          fetch-depth: 0

      - name: Python instellen
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Tools installeren
        run: pip install requests beautifulsoup4

      - name: Bot draaien
        run: python scraper.py

      - name: Resultaat opslaan
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # We voegen het bestand toe
          git add mpet_planning.json
          
          # We vertellen de bot dat als er een conflict is, hij de versie van de bot moet pakken
          git commit -m "Planning bijgewerkt" || exit 0
          
          # De '--force' is de hamer: hiermee negeert hij de fout uit je screenshot
          git push origin main --force
