    - name: Resultaat opslaan
      run: |
        git config --global user.name "MPET Bot"
        git config --global user.email "bot@github.com"
        git fetch origin main
        git reset --soft origin/main
        git add mpet_planning.json
        git commit -m "Update planning" || exit 0
        git push origin main --force
